sportSiteMvc/Models/Exercise.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;

namespace sportSiteMvc.Models
{
    public class Exercise
    {
        [Key, ScaffoldColumn(false)]
        public int ExerciseId { get; set; }

        [Required, StringLength(255), Display(Name = "Title")]
        public string ExerciseTitle { get; set; }

        [StringLength(255), Display(Name = "Photo")]
        public string ExercisePhoto { get; set; }

        [StringLength(int.MaxValue), Display(Name = "Content")]
        public string ExerciseContent { get; set; }

        //One excersise to many muscel groups
        public virtual ICollection<MuscleGroup> MuscleGroups { get; set; }

    }
}

sportSiteMvc/Controllers/ExerciseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.SqlClient;
using System.Data.Entity;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using sportSiteMvc.Models;

namespace sportSiteMvc.Controllers
{
    public class ExerciseController : Controller
    {

        MuscleGroupsContext db = new MuscleGroupsContext();
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }
        //================================================================================= Read

        public ActionResult List()
        {

            string query = "select * from Exercises";
            // Обьявить переменную
            IEnumerable<Exercise> exercises;
            exercises = db.Exercises.SqlQuery(query);

            return View(exercises);
        }
        //================================================================================= Create

        public ActionResult Create()
        {
            return List();
        }

        [HttpPost]
        public ActionResult Create(string ExerciseTitle, string ExercisePhoto, string ExerciseContent)
        {
            string query = "insert into Exercises (ExerciseTitle, ExercisePhoto, ExerciseContent)" +
                " values (@title, @photo, @content)";
            SqlParameter[] myparams = new SqlParameter[3];
            myparams[0] = new SqlParameter("@title", ExerciseTitle);
            myparams[1] = new SqlParameter("@photo", ExercisePhoto);
            myparams[2] = new SqlParameter("@content", ExerciseContent);

            Debug.WriteLine(query);
            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("List");
        }
        
        //================================================================================= Edit

        public ActionResult Edit(int? id)
        {
            if ((id == null) || (db.Exercises.Find(id) == null))
            {
                return HttpNotFound();
            }
            string query = "select * from Exercises where ExerciseId=@id";
            SqlParameter param = new SqlParameter("@id", id);
            Exercise mytag = db.Exercises.SqlQuery(query, param).FirstOrDefault();
            return View(mytag);
        }

        [HttpPost]
        public ActionResult Edit(int? id, string ExerciseTitle, string ExercisePhoto, string ExerciseContent)
        {
            if ((id == null) || (db.Exercises.Find(id) == null))
            {
                return HttpNotFound();
            }
            string query = "update Exercises set ExerciseTitle=@title, ExercisePhoto=@photo, ExerciseContent=@content" +
                " where ExerciseId=@id";
            SqlParameter[] myparams = new SqlParameter[4];
            myparams[0] = new SqlParameter("@title", ExerciseTitle);
            myparams[1] = new SqlParameter("@photo", ExercisePhoto);
            myparams[2] = new SqlParameter("@content", ExerciseContent);
            myparams[3] = new SqlParameter("@id", id);

            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("List");
        }
       
        //================================================================================= Delete

        public ActionResult Delete(int? id)
        {

            if ((id == null) || (db.Exercises.Find(id) == null))
            {
                return HttpNotFound();

            }
            string query = "delete from Exercises where ExerciseId=@id";
            SqlParameter param = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query, param);
            return RedirectToAction("List");

        }
  
        //================================================================================= Details
        public ActionResult Details(int? id)
        {
            if ((id == null) || (db.Exercises.Find(id) == null))
            {
                return HttpNotFound();

            }
            string query = "select * from Exercises whereExerciseId=@id";
            SqlParameter param = new SqlParameter("@id", id);

            Exercise Exercisestoshow = db.Exercises.Find(id);

            return View(Exercisestoshow);
        }
    }

    
}

sportSiteMvc/Views/Exercise/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Create Exercise</h2>

<form method="POST" action="/Exercise/Create">
    <div>
        <div>Title:</div>
        <input type="text" id="ExerciseTitle_New" name="ExerciseTitle" />
    </div>
    <div>
        <div>Photo:</div>
        <input type="text" id="ExercisePhoto_New" name="ExercisePhoto" />
    </div>
    <div>
        <div>Content:</div>
        <input type="text" id="ExerciseContent_New" name="ExerciseContent" />
    </div>

    <div>
        <input type="submit" value="Submit" />
    </div>


</form>

sportSiteMvc/Views/Exercise/Delete.cshtml
@model sportSiteMvc.Models.Exercise

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

sportSiteMvc/Views/Exercise/Details.cshtml
@model sportSiteMvc.Models.Exercise

@{
    ViewBag.Title = "Details";
}

<h2>@Model.ExerciseTitle</h2>


<div class="content">
    <p>@Model.ExercisePhoto</p>
    <p>@Model.ExerciseContent</p>
</div>

<p class="edd position">
    @Html.ActionLink("Back to List", "List")
</p>
<p class="edd position">
    @Html.ActionLink("Edit", "Edit/" + Model.ExerciseId)
</p>

sportSiteMvc/Views/Exercise/Edit.cshtml
@model sportSiteMvc.Models.Exercise

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<form method="POST" action="/Exercise/Edit/@Model.ExerciseId">
    <div>
        <label>Title</label>
        <input type="text" value="@Model.ExerciseTitle" id="ExerciseTitle" name="ExerciseTitle" />
    </div>
    <div>
        <label>Photo</label>
        <input type="text" value="@Model.ExercisePhoto" id="ExercisePhoto" name="ExercisePhoto" />
    </div>
    <div>
        <label>Content</label>
        <input type="text" value="@Model.ExerciseContent" id="ExerciseContent" name="ExerciseContent" />
    </div>
    <div>
        <input type="submit" value="Submit" />
    </div>
</form>
<p class="edd">
    @Html.ActionLink("Back to List", "List")
</p>

sportSiteMvc/Views/Exercise/List.cshtml
@model IEnumerable<sportSiteMvc.Models.Exercise>

@{
    ViewBag.Title = "List";
}

<div>
    <h2>Exercise</h2>
</div>

<div>
    @foreach (var exercise in Model)
    {
    <div class="group_container">
        <div class="title">
            <h3>
                @Html.ActionLink(exercise.ExerciseTitle, "Details/" + exercise.ExerciseId, "Exercise")
            </h3>
        </div>
        <p class="options edd">
            @Html.ActionLink("Edit", "Edit", new { id = exercise.ExerciseId }) |
            @Html.ActionLink("Delete", "Delete", new { id = exercise.ExerciseId })
        </p>
        <div class="clear"></div>
    </div>
    }
</div>

<div class="create_new">
    @Html.ActionLink("New Exercise", "Create", "Exercise")
</div>